config/routes.rb
KyuentaDb::Application.routes.draw do
  devise_for :users

  resources :accounts

  resources :people

  resources :donations

  resources :addresses

  root :to => "people#index"

end

app/models/person.rb
class Person < ActiveRecord::Base
  
  has_many :addresses
  has_many :donations
  has_many :accounts

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.xml
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @people }
    end
  end

  # GET /people/1
  # GET /people/1.xml
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/new
  # GET /people/new.xml
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.xml
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to(@person, :notice => 'Person was successfully created.') }
        format.xml  { render :xml => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to(@person, :notice => 'Person was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= simple_form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :name %><br />
  </div>
  <div class="field">
    <%= f.collection_radio :klass, [["LegalPerson", 'Juristische Person'] ,["NaturalPerson", 'Natuerliche Person']], :first, :last %>
  </div>
  <div class="field">
    <%= f.input :last_name %>
  </div>
  <div class="field">
    <%= f.input :sex %>
  </div>
  <div class="field">
    <%= f.input :number %>
  </div>
  <div class="field">
    <%= f.input :telephone %>
  </div>
  <div class="field">
    <%= f.input :date_of_joining %>
  </div>
  <div class="field">
    <%= f.input :date_of_birth, :start_year => Date.today.year - 90,
                                :end_year => Date.today.year - 12 %>
  </div>
  <div class="field">
    <%= f.input :nationality %>
  </div>
  <div class="field">
    <%= f.input :email %>
  </div>
  <div class="field">
    <%= f.association :addresses %>
  </div>
  <div class="field">
    <%= f.association :accounts%>
  </div>
  <div class="field">
    <%= f.association :donations %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.klass%></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Vorname:</b>
  <%= @person.name %>
</p>

<p>
  <b>Nachname:</b>
  <%= @person.last_name %>
</p>

<p>
  <b>Geschlecht:</b>
  <%= @person.sex %>
</p>

<p>
  <b>Telefon:</b>
  <%= @person.telephone %>
</p>

<p>
  <b>Mitgliedsnummer:</b>
  <%= @person.number %>
</p>

<p>
  <b>Eintrittsdatum:</b>
  <%= @person.date_of_joining %>
</p>

<p>
  <b>Geburtsdatum:</b>
  <%= @person.date_of_birth %>
</p>

<p>
  <b>Nationalität:</b>
  <%= @person.nationality %>
</p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>

<p>
  <b>Type:</b>
  <%= @person.klass %>
</p>

<h2>Adressen</h2>
<div id="addresses">
  <p>
    <% @person.addresses.each do |address| %>
      <%= address.street %> <br>
      <%= address.zip %> <br>
      <%= address.city %> <br>
      <%= address.misc %> <br>
      <%= link_to "Bearbeiten", edit_address_path(address) %>
    <% end %>
  </p>
</div>

<h2>Konten</h2>
<div id="accounts">
  <p>
    <% @person.accounts.each do |account| %>
      <%= account.owner%> <br>
      <%= account.bic %> <br>
      <%= account.iban %> <br>
      <%= account.bank_code %> <br>
      <%= account.number %> <br>
      <%= link_to "Bearbeiten", edit_account_path(account) %>
    <% end %>
  </p>
</div>

<h2>Spenden</h2>
<div id="donations">
  <p>
    <% @person.donations.each do |donation| %>
      <%= donation.amount%> <br>
      <%= donation.recurring ? "Dauerhaft" : "Einzelspende"  %> <br>
      <%= link_to "Bearbeiten", edit_donation_path(donation) %>
    <% end %>
  </p>
</div>
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>